
// This file has been generated by the GUI designer. Do not modify.
namespace PublishGUI
{
	public partial class CsvToLrWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PublishGUI.CsvToLrWindow
			this.Name = "PublishGUI.CsvToLrWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("CsvToLrWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
