
// This file has been generated by the GUI designer. Do not modify.

public partial class CsvToLrWindow
{
	private global::Gtk.VBox MapRowsContainer;
	private global::Gtk.Label lbl_CsvInstructions;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget CsvToLrWindow
		this.Name = "CsvToLrWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Import From CSV");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child CsvToLrWindow.Gtk.Container+ContainerChild
		this.MapRowsContainer = new global::Gtk.VBox ();
		this.MapRowsContainer.Name = "MapRowsContainer";
		this.MapRowsContainer.Spacing = 6;
		// Container child MapRowsContainer.Gtk.Box+BoxChild
		this.lbl_CsvInstructions = new global::Gtk.Label ();
		this.lbl_CsvInstructions.WidthRequest = 500;
		this.lbl_CsvInstructions.Name = "lbl_CsvInstructions";
		this.lbl_CsvInstructions.Xpad = 6;
		this.lbl_CsvInstructions.Ypad = 5;
		this.lbl_CsvInstructions.Xalign = 0F;
		this.lbl_CsvInstructions.LabelProp = global::Mono.Unix.Catalog.GetString ("For each item on the left, choose the approprate column from the csv file that co" +
				"rresponds to the element of the resource description data model on the right:");
		this.lbl_CsvInstructions.Wrap = true;
		this.MapRowsContainer.Add (this.lbl_CsvInstructions);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.MapRowsContainer [this.lbl_CsvInstructions]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		this.Add (this.MapRowsContainer);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 500;
		this.DefaultHeight = 300;
		this.Show ();
	}
}
