
// This file has been generated by the GUI designer. Do not modify.
namespace PublishGUI
{
	public partial class CsvToLrMapRow
	{
		private global::Gtk.HBox RowContainer;
		private global::Gtk.ComboBox ColumnOptionsComboBox;
		private global::Gtk.Label lbl_MapsTo;
		private global::Gtk.Label lbl_ResourceDataField;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PublishGUI.CsvToLrMapRow
			global::Stetic.BinContainer.Attach (this);
			this.Name = "PublishGUI.CsvToLrMapRow";
			// Container child PublishGUI.CsvToLrMapRow.Gtk.Container+ContainerChild
			this.RowContainer = new global::Gtk.HBox ();
			this.RowContainer.Name = "RowContainer";
			this.RowContainer.Spacing = 6;
			// Container child RowContainer.Gtk.Box+BoxChild
			this.ColumnOptionsComboBox = global::Gtk.ComboBox.NewText ();
			this.ColumnOptionsComboBox.Name = "ColumnOptionsComboBox";
			this.RowContainer.Add (this.ColumnOptionsComboBox);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.RowContainer [this.ColumnOptionsComboBox]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child RowContainer.Gtk.Box+BoxChild
			this.lbl_MapsTo = new global::Gtk.Label ();
			this.lbl_MapsTo.Name = "lbl_MapsTo";
			this.lbl_MapsTo.LabelProp = global::Mono.Unix.Catalog.GetString ("Maps To:");
			this.RowContainer.Add (this.lbl_MapsTo);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.RowContainer [this.lbl_MapsTo]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child RowContainer.Gtk.Box+BoxChild
			this.lbl_ResourceDataField = new global::Gtk.Label ();
			this.lbl_ResourceDataField.Name = "lbl_ResourceDataField";
			this.RowContainer.Add (this.lbl_ResourceDataField);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.RowContainer [this.lbl_ResourceDataField]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.Add (this.RowContainer);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
