
// This file has been generated by the GUI designer. Do not modify.

public partial class HistoryWindow
{
	private global::Gtk.VBox ScrollContainerContainerLolZomg;
	private global::Gtk.ScrolledWindow ScrollContainer;
	private global::Gtk.VBox HistoryTable;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget HistoryWindow
		this.Name = "HistoryWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("HistoryWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child HistoryWindow.Gtk.Container+ContainerChild
		this.ScrollContainerContainerLolZomg = new global::Gtk.VBox ();
		this.ScrollContainerContainerLolZomg.Name = "ScrollContainerContainerLolZomg";
		this.ScrollContainerContainerLolZomg.Spacing = 6;
		// Container child ScrollContainerContainerLolZomg.Gtk.Box+BoxChild
		this.ScrollContainer = new global::Gtk.ScrolledWindow ();
		this.ScrollContainer.CanFocus = true;
		this.ScrollContainer.Name = "ScrollContainer";
		this.ScrollContainer.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child ScrollContainer.Gtk.Container+ContainerChild
		global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
		w1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.HistoryTable = new global::Gtk.VBox ();
		this.HistoryTable.Name = "HistoryTable";
		this.HistoryTable.Spacing = 6;
		w1.Add (this.HistoryTable);
		this.ScrollContainer.Add (w1);
		this.ScrollContainerContainerLolZomg.Add (this.ScrollContainer);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.ScrollContainerContainerLolZomg [this.ScrollContainer]));
		w4.Position = 0;
		this.Add (this.ScrollContainerContainerLolZomg);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 498;
		this.DefaultHeight = 495;
		this.Show ();
	}
}
