
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action OpenResourceDescriptionAction;
	private global::Gtk.Action SaveResourceDescriptionAction;
	private global::Gtk.Action PublishAction;
	private global::Gtk.Action PublishCurrentDocumentAction;
	private global::Gtk.Action PublishFromFolderAction;
	private global::Gtk.Action NewAction;
	private global::Gtk.Action PublishFromCSVAction;
	private global::Gtk.Action HistoryAction;
	private global::Gtk.Action ViewPublishHistoryAction;
	private global::Gtk.VBox MainVerticalPane;
	private global::Gtk.MenuBar MainMenu;
	private global::Gtk.Notebook RootNotebook;
	private global::Gtk.HBox ResourceDescriptionContainer;
	private global::Gtk.VBox ResourceDescriptionColumn1;
	private global::Gtk.Label lbl_ResourceDataType;
	private global::Gtk.ComboBox ResourceDataTypeComboBox;
	private global::Gtk.Label lbl_ResourceLocator;
	private global::Gtk.Entry ResourceLocatorTextBox;
	private global::Gtk.Label lbl_PayloadPlacement;
	private global::Gtk.ComboBox PayloadPlacementComboBox;
	private global::Gtk.VBox PayloadChooseContainer;
	private global::Gtk.VBox PayloadFileContainer;
	private global::Gtk.Label lbl_PayloadFile;
	private global::Gtk.FileChooserButton PayloadFileChooser;
	private global::Gtk.VBox PayloadLocatorContainer;
	private global::Gtk.Label lbl_PayloadLocator;
	private global::Gtk.Entry PayloadLocatorTextBox;
	private global::Gtk.HButtonBox PayloadEditorButtonBox;
	private global::Gtk.Button EditPayloadButton;
	private global::Gtk.Button ChoosePayloadFileButton;
	private global::Gtk.Label lbl_PayloadSchema;
	private global::Gtk.Entry PayloadSchemaTextBox;
	private global::Gtk.VBox ResourceDescriptionColumn2;
	private global::Gtk.Label lbl_SchemaLocator;
	private global::Gtk.Entry PayloadSchemaLocatorTextBox;
	private global::Gtk.Label lbl_SchemaFormat;
	private global::Gtk.Entry SchemaFormatTextBox;
	private global::Gtk.Label lbl_Keywords;
	private global::Gtk.Entry KeywordsTextBox;
	private global::Gtk.Label lbl_TimeToLive;
	private global::Gtk.HBox TTLFieldContainer;
	private global::Gtk.Entry TimeToLiveTextBox;
	private global::Gtk.Label lbl_Days;
	private global::Gtk.VBox ResourceDescriptionColumn3;
	private global::Gtk.Label lbl_SubmitterType;
	private global::Gtk.ComboBox SubmitterTypeComboBox;
	private global::Gtk.VBox SubmitterNameContainer;
	private global::Gtk.Label lbl_SubmitterName;
	private global::Gtk.Entry SubmitterNameTextBox;
	private global::Gtk.Label lbl_Curator;
	private global::Gtk.Entry CuratorTextBox;
	private global::Gtk.Label lbl_Owner;
	private global::Gtk.Entry OwnerTextBox;
	private global::Gtk.Label lbl_Signer;
	private global::Gtk.Entry SignerTextBox;
	private global::Gtk.Label lbl_nb_ResourceDescription;
	private global::Gtk.VBox TermsOfServiceContainer;
	private global::Gtk.Label lbl_TermsOfServiceUrl;
	private global::Gtk.Entry TermsOfServiceTextBox;
	private global::Gtk.Label lbl_AttributionStatement;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView AttributionStatementTextView;
	private global::Gtk.Label lbl_nb_TermsOfService;
	private global::SignatureInformationWidget SignatureInformationWidget;
	private global::Gtk.Label lbl_nb_SignatureInformation;
	private global::Gtk.HBox NodeInformationContainer;
	private global::NodeInfoWidget NodeInfo;
	private global::Gtk.Label lbl_nb_NodeInformation;
	private global::Gtk.HBox RequiredFieldNotificationContainer;
	private global::Gtk.Label lbl_requiredFieldsNotifier;
	private global::Gtk.Label lbl_ConsoleOutput;
	private global::Gtk.ScrolledWindow ConsoleContainer;
	private global::Gtk.TextView ConsoleWindow;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.OpenResourceDescriptionAction = new global::Gtk.Action ("OpenResourceDescriptionAction", global::Mono.Unix.Catalog.GetString ("Open Resource Description..."), null, null);
		this.OpenResourceDescriptionAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open Resource Description...");
		w1.Add (this.OpenResourceDescriptionAction, null);
		this.SaveResourceDescriptionAction = new global::Gtk.Action ("SaveResourceDescriptionAction", global::Mono.Unix.Catalog.GetString ("Save Resource Description..."), null, null);
		this.SaveResourceDescriptionAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save Resource Description...");
		w1.Add (this.SaveResourceDescriptionAction, null);
		this.PublishAction = new global::Gtk.Action ("PublishAction", global::Mono.Unix.Catalog.GetString ("Publish"), null, null);
		this.PublishAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Publish");
		w1.Add (this.PublishAction, null);
		this.PublishCurrentDocumentAction = new global::Gtk.Action ("PublishCurrentDocumentAction", global::Mono.Unix.Catalog.GetString ("Publish Current Document"), null, null);
		this.PublishCurrentDocumentAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Publish Current Document");
		w1.Add (this.PublishCurrentDocumentAction, null);
		this.PublishFromFolderAction = new global::Gtk.Action ("PublishFromFolderAction", global::Mono.Unix.Catalog.GetString ("Publish From Folder..."), null, null);
		this.PublishFromFolderAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Publish From Folder...");
		w1.Add (this.PublishFromFolderAction, null);
		this.NewAction = new global::Gtk.Action ("NewAction", global::Mono.Unix.Catalog.GetString ("New"), null, null);
		this.NewAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New");
		w1.Add (this.NewAction, null);
		this.PublishFromCSVAction = new global::Gtk.Action ("PublishFromCSVAction", global::Mono.Unix.Catalog.GetString ("Publish From CSV..."), null, null);
		this.PublishFromCSVAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Publish From CSV");
		w1.Add (this.PublishFromCSVAction, null);
		this.HistoryAction = new global::Gtk.Action ("HistoryAction", global::Mono.Unix.Catalog.GetString ("History"), null, null);
		this.HistoryAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("History");
		w1.Add (this.HistoryAction, null);
		this.ViewPublishHistoryAction = new global::Gtk.Action ("ViewPublishHistoryAction", global::Mono.Unix.Catalog.GetString ("View Publish History"), null, null);
		this.ViewPublishHistoryAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("View Publish History");
		w1.Add (this.ViewPublishHistoryAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Learning Registry Publishing Tool");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.MainVerticalPane = new global::Gtk.VBox ();
		this.MainVerticalPane.Name = "MainVerticalPane";
		this.MainVerticalPane.Spacing = 6;
		this.MainVerticalPane.BorderWidth = ((uint)(6));
		// Container child MainVerticalPane.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString (@"<ui><menubar name='MainMenu'><menu name='FileAction' action='FileAction'><menuitem name='NewAction' action='NewAction'/><menuitem name='OpenResourceDescriptionAction' action='OpenResourceDescriptionAction'/><menuitem name='SaveResourceDescriptionAction' action='SaveResourceDescriptionAction'/></menu><menu name='PublishAction' action='PublishAction'><menuitem name='PublishCurrentDocumentAction' action='PublishCurrentDocumentAction'/><menuitem name='PublishFromCSVAction' action='PublishFromCSVAction'/></menu><menu name='HistoryAction' action='HistoryAction'><menuitem name='ViewPublishHistoryAction' action='ViewPublishHistoryAction'/></menu></menubar></ui>");
		this.MainMenu = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/MainMenu")));
		this.MainMenu.Name = "MainMenu";
		this.MainVerticalPane.Add (this.MainMenu);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.MainVerticalPane [this.MainMenu]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child MainVerticalPane.Gtk.Box+BoxChild
		this.RootNotebook = new global::Gtk.Notebook ();
		this.RootNotebook.CanFocus = true;
		this.RootNotebook.Name = "RootNotebook";
		this.RootNotebook.CurrentPage = 0;
		// Container child RootNotebook.Gtk.Notebook+NotebookChild
		this.ResourceDescriptionContainer = new global::Gtk.HBox ();
		this.ResourceDescriptionContainer.Name = "ResourceDescriptionContainer";
		this.ResourceDescriptionContainer.Spacing = 6;
		this.ResourceDescriptionContainer.BorderWidth = ((uint)(9));
		// Container child ResourceDescriptionContainer.Gtk.Box+BoxChild
		this.ResourceDescriptionColumn1 = new global::Gtk.VBox ();
		this.ResourceDescriptionColumn1.Name = "ResourceDescriptionColumn1";
		this.ResourceDescriptionColumn1.Spacing = 6;
		// Container child ResourceDescriptionColumn1.Gtk.Box+BoxChild
		this.lbl_ResourceDataType = new global::Gtk.Label ();
		this.lbl_ResourceDataType.Name = "lbl_ResourceDataType";
		this.lbl_ResourceDataType.Xalign = 0F;
		this.lbl_ResourceDataType.LabelProp = global::Mono.Unix.Catalog.GetString ("*Resource Data Type:");
		this.ResourceDescriptionColumn1.Add (this.lbl_ResourceDataType);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionColumn1 [this.lbl_ResourceDataType]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child ResourceDescriptionColumn1.Gtk.Box+BoxChild
		this.ResourceDataTypeComboBox = global::Gtk.ComboBox.NewText ();
		this.ResourceDataTypeComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Metadata"));
		this.ResourceDataTypeComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Paradata"));
		this.ResourceDataTypeComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Resource"));
		this.ResourceDataTypeComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Assertion"));
		this.ResourceDataTypeComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Other"));
		this.ResourceDataTypeComboBox.Name = "ResourceDataTypeComboBox";
		this.ResourceDataTypeComboBox.Active = 0;
		this.ResourceDescriptionColumn1.Add (this.ResourceDataTypeComboBox);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionColumn1 [this.ResourceDataTypeComboBox]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child ResourceDescriptionColumn1.Gtk.Box+BoxChild
		this.lbl_ResourceLocator = new global::Gtk.Label ();
		this.lbl_ResourceLocator.Name = "lbl_ResourceLocator";
		this.lbl_ResourceLocator.Xalign = 0F;
		this.lbl_ResourceLocator.LabelProp = global::Mono.Unix.Catalog.GetString ("*Resource Locator:");
		this.ResourceDescriptionColumn1.Add (this.lbl_ResourceLocator);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionColumn1 [this.lbl_ResourceLocator]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		// Container child ResourceDescriptionColumn1.Gtk.Box+BoxChild
		this.ResourceLocatorTextBox = new global::Gtk.Entry ();
		this.ResourceLocatorTextBox.CanFocus = true;
		this.ResourceLocatorTextBox.Name = "ResourceLocatorTextBox";
		this.ResourceLocatorTextBox.IsEditable = true;
		this.ResourceLocatorTextBox.InvisibleChar = '●';
		this.ResourceDescriptionColumn1.Add (this.ResourceLocatorTextBox);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionColumn1 [this.ResourceLocatorTextBox]));
		w6.Position = 3;
		w6.Expand = false;
		w6.Fill = false;
		// Container child ResourceDescriptionColumn1.Gtk.Box+BoxChild
		this.lbl_PayloadPlacement = new global::Gtk.Label ();
		this.lbl_PayloadPlacement.Name = "lbl_PayloadPlacement";
		this.lbl_PayloadPlacement.Xalign = 0F;
		this.lbl_PayloadPlacement.LabelProp = global::Mono.Unix.Catalog.GetString ("*Payload Placement:");
		this.ResourceDescriptionColumn1.Add (this.lbl_PayloadPlacement);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionColumn1 [this.lbl_PayloadPlacement]));
		w7.Position = 4;
		w7.Expand = false;
		w7.Fill = false;
		// Container child ResourceDescriptionColumn1.Gtk.Box+BoxChild
		this.PayloadPlacementComboBox = global::Gtk.ComboBox.NewText ();
		this.PayloadPlacementComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Inline"));
		this.PayloadPlacementComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Linked"));
		this.PayloadPlacementComboBox.AppendText ("");
		this.PayloadPlacementComboBox.Name = "PayloadPlacementComboBox";
		this.PayloadPlacementComboBox.Active = 0;
		this.ResourceDescriptionColumn1.Add (this.PayloadPlacementComboBox);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionColumn1 [this.PayloadPlacementComboBox]));
		w8.Position = 5;
		w8.Expand = false;
		w8.Fill = false;
		// Container child ResourceDescriptionColumn1.Gtk.Box+BoxChild
		this.PayloadChooseContainer = new global::Gtk.VBox ();
		this.PayloadChooseContainer.Name = "PayloadChooseContainer";
		this.PayloadChooseContainer.Spacing = 6;
		// Container child PayloadChooseContainer.Gtk.Box+BoxChild
		this.PayloadFileContainer = new global::Gtk.VBox ();
		this.PayloadFileContainer.Name = "PayloadFileContainer";
		this.PayloadFileContainer.Spacing = 6;
		// Container child PayloadFileContainer.Gtk.Box+BoxChild
		this.lbl_PayloadFile = new global::Gtk.Label ();
		this.lbl_PayloadFile.Name = "lbl_PayloadFile";
		this.lbl_PayloadFile.Xalign = 0F;
		this.lbl_PayloadFile.LabelProp = global::Mono.Unix.Catalog.GetString ("*Payload File:");
		this.PayloadFileContainer.Add (this.lbl_PayloadFile);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.PayloadFileContainer [this.lbl_PayloadFile]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child PayloadFileContainer.Gtk.Box+BoxChild
		this.PayloadFileChooser = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select A File"), ((global::Gtk.FileChooserAction)(0)));
		this.PayloadFileChooser.Name = "PayloadFileChooser";
		this.PayloadFileContainer.Add (this.PayloadFileChooser);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.PayloadFileContainer [this.PayloadFileChooser]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		this.PayloadChooseContainer.Add (this.PayloadFileContainer);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.PayloadChooseContainer [this.PayloadFileContainer]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child PayloadChooseContainer.Gtk.Box+BoxChild
		this.PayloadLocatorContainer = new global::Gtk.VBox ();
		this.PayloadLocatorContainer.Name = "PayloadLocatorContainer";
		this.PayloadLocatorContainer.Spacing = 6;
		// Container child PayloadLocatorContainer.Gtk.Box+BoxChild
		this.lbl_PayloadLocator = new global::Gtk.Label ();
		this.lbl_PayloadLocator.Name = "lbl_PayloadLocator";
		this.lbl_PayloadLocator.Xalign = 0F;
		this.lbl_PayloadLocator.LabelProp = global::Mono.Unix.Catalog.GetString ("*Payload Locator:");
		this.PayloadLocatorContainer.Add (this.lbl_PayloadLocator);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.PayloadLocatorContainer [this.lbl_PayloadLocator]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child PayloadLocatorContainer.Gtk.Box+BoxChild
		this.PayloadLocatorTextBox = new global::Gtk.Entry ();
		this.PayloadLocatorTextBox.CanFocus = true;
		this.PayloadLocatorTextBox.Name = "PayloadLocatorTextBox";
		this.PayloadLocatorTextBox.IsEditable = true;
		this.PayloadLocatorTextBox.InvisibleChar = '●';
		this.PayloadLocatorContainer.Add (this.PayloadLocatorTextBox);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.PayloadLocatorContainer [this.PayloadLocatorTextBox]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		this.PayloadChooseContainer.Add (this.PayloadLocatorContainer);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.PayloadChooseContainer [this.PayloadLocatorContainer]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		// Container child PayloadChooseContainer.Gtk.Box+BoxChild
		this.PayloadEditorButtonBox = new global::Gtk.HButtonBox ();
		this.PayloadEditorButtonBox.Name = "PayloadEditorButtonBox";
		// Container child PayloadEditorButtonBox.Gtk.ButtonBox+ButtonBoxChild
		this.EditPayloadButton = new global::Gtk.Button ();
		this.EditPayloadButton.CanFocus = true;
		this.EditPayloadButton.Name = "EditPayloadButton";
		this.EditPayloadButton.UseUnderline = true;
		this.EditPayloadButton.Label = global::Mono.Unix.Catalog.GetString ("Edit Data");
		this.PayloadEditorButtonBox.Add (this.EditPayloadButton);
		global::Gtk.ButtonBox.ButtonBoxChild w15 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.PayloadEditorButtonBox [this.EditPayloadButton]));
		w15.Expand = false;
		w15.Fill = false;
		// Container child PayloadEditorButtonBox.Gtk.ButtonBox+ButtonBoxChild
		this.ChoosePayloadFileButton = new global::Gtk.Button ();
		this.ChoosePayloadFileButton.CanFocus = true;
		this.ChoosePayloadFileButton.Name = "ChoosePayloadFileButton";
		this.ChoosePayloadFileButton.UseUnderline = true;
		this.ChoosePayloadFileButton.Label = global::Mono.Unix.Catalog.GetString ("Choose File...");
		this.PayloadEditorButtonBox.Add (this.ChoosePayloadFileButton);
		global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.PayloadEditorButtonBox [this.ChoosePayloadFileButton]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		this.PayloadChooseContainer.Add (this.PayloadEditorButtonBox);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.PayloadChooseContainer [this.PayloadEditorButtonBox]));
		w17.Position = 2;
		w17.Expand = false;
		w17.Fill = false;
		this.ResourceDescriptionColumn1.Add (this.PayloadChooseContainer);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionColumn1 [this.PayloadChooseContainer]));
		w18.Position = 6;
		w18.Expand = false;
		w18.Fill = false;
		// Container child ResourceDescriptionColumn1.Gtk.Box+BoxChild
		this.lbl_PayloadSchema = new global::Gtk.Label ();
		this.lbl_PayloadSchema.Name = "lbl_PayloadSchema";
		this.lbl_PayloadSchema.Xalign = 0F;
		this.lbl_PayloadSchema.LabelProp = global::Mono.Unix.Catalog.GetString ("*Payload Schema:");
		this.ResourceDescriptionColumn1.Add (this.lbl_PayloadSchema);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionColumn1 [this.lbl_PayloadSchema]));
		w19.Position = 7;
		w19.Expand = false;
		w19.Fill = false;
		// Container child ResourceDescriptionColumn1.Gtk.Box+BoxChild
		this.PayloadSchemaTextBox = new global::Gtk.Entry ();
		this.PayloadSchemaTextBox.CanFocus = true;
		this.PayloadSchemaTextBox.Name = "PayloadSchemaTextBox";
		this.PayloadSchemaTextBox.IsEditable = true;
		this.PayloadSchemaTextBox.InvisibleChar = '●';
		this.ResourceDescriptionColumn1.Add (this.PayloadSchemaTextBox);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionColumn1 [this.PayloadSchemaTextBox]));
		w20.Position = 8;
		w20.Expand = false;
		w20.Fill = false;
		this.ResourceDescriptionContainer.Add (this.ResourceDescriptionColumn1);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionContainer [this.ResourceDescriptionColumn1]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		w21.Padding = ((uint)(10));
		// Container child ResourceDescriptionContainer.Gtk.Box+BoxChild
		this.ResourceDescriptionColumn2 = new global::Gtk.VBox ();
		this.ResourceDescriptionColumn2.Name = "ResourceDescriptionColumn2";
		this.ResourceDescriptionColumn2.Spacing = 6;
		// Container child ResourceDescriptionColumn2.Gtk.Box+BoxChild
		this.lbl_SchemaLocator = new global::Gtk.Label ();
		this.lbl_SchemaLocator.Name = "lbl_SchemaLocator";
		this.lbl_SchemaLocator.Xalign = 0F;
		this.lbl_SchemaLocator.LabelProp = global::Mono.Unix.Catalog.GetString ("Schema Locator:");
		this.ResourceDescriptionColumn2.Add (this.lbl_SchemaLocator);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionColumn2 [this.lbl_SchemaLocator]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		// Container child ResourceDescriptionColumn2.Gtk.Box+BoxChild
		this.PayloadSchemaLocatorTextBox = new global::Gtk.Entry ();
		this.PayloadSchemaLocatorTextBox.CanFocus = true;
		this.PayloadSchemaLocatorTextBox.Name = "PayloadSchemaLocatorTextBox";
		this.PayloadSchemaLocatorTextBox.IsEditable = true;
		this.PayloadSchemaLocatorTextBox.InvisibleChar = '●';
		this.ResourceDescriptionColumn2.Add (this.PayloadSchemaLocatorTextBox);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionColumn2 [this.PayloadSchemaLocatorTextBox]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		// Container child ResourceDescriptionColumn2.Gtk.Box+BoxChild
		this.lbl_SchemaFormat = new global::Gtk.Label ();
		this.lbl_SchemaFormat.Name = "lbl_SchemaFormat";
		this.lbl_SchemaFormat.Xalign = 0F;
		this.lbl_SchemaFormat.LabelProp = global::Mono.Unix.Catalog.GetString ("Schema MIME Type:");
		this.ResourceDescriptionColumn2.Add (this.lbl_SchemaFormat);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionColumn2 [this.lbl_SchemaFormat]));
		w24.Position = 2;
		w24.Expand = false;
		w24.Fill = false;
		// Container child ResourceDescriptionColumn2.Gtk.Box+BoxChild
		this.SchemaFormatTextBox = new global::Gtk.Entry ();
		this.SchemaFormatTextBox.CanFocus = true;
		this.SchemaFormatTextBox.Name = "SchemaFormatTextBox";
		this.SchemaFormatTextBox.IsEditable = true;
		this.SchemaFormatTextBox.InvisibleChar = '●';
		this.ResourceDescriptionColumn2.Add (this.SchemaFormatTextBox);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionColumn2 [this.SchemaFormatTextBox]));
		w25.Position = 3;
		w25.Expand = false;
		w25.Fill = false;
		// Container child ResourceDescriptionColumn2.Gtk.Box+BoxChild
		this.lbl_Keywords = new global::Gtk.Label ();
		this.lbl_Keywords.Name = "lbl_Keywords";
		this.lbl_Keywords.Xalign = 0F;
		this.lbl_Keywords.LabelProp = global::Mono.Unix.Catalog.GetString ("Keywords (separated by commas):");
		this.ResourceDescriptionColumn2.Add (this.lbl_Keywords);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionColumn2 [this.lbl_Keywords]));
		w26.Position = 4;
		w26.Expand = false;
		w26.Fill = false;
		// Container child ResourceDescriptionColumn2.Gtk.Box+BoxChild
		this.KeywordsTextBox = new global::Gtk.Entry ();
		this.KeywordsTextBox.CanFocus = true;
		this.KeywordsTextBox.Name = "KeywordsTextBox";
		this.KeywordsTextBox.IsEditable = true;
		this.KeywordsTextBox.InvisibleChar = '●';
		this.ResourceDescriptionColumn2.Add (this.KeywordsTextBox);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionColumn2 [this.KeywordsTextBox]));
		w27.Position = 5;
		w27.Expand = false;
		w27.Fill = false;
		// Container child ResourceDescriptionColumn2.Gtk.Box+BoxChild
		this.lbl_TimeToLive = new global::Gtk.Label ();
		this.lbl_TimeToLive.Name = "lbl_TimeToLive";
		this.lbl_TimeToLive.Xalign = 0F;
		this.lbl_TimeToLive.LabelProp = global::Mono.Unix.Catalog.GetString ("Time To Live:");
		this.ResourceDescriptionColumn2.Add (this.lbl_TimeToLive);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionColumn2 [this.lbl_TimeToLive]));
		w28.Position = 6;
		w28.Expand = false;
		w28.Fill = false;
		// Container child ResourceDescriptionColumn2.Gtk.Box+BoxChild
		this.TTLFieldContainer = new global::Gtk.HBox ();
		this.TTLFieldContainer.Name = "TTLFieldContainer";
		this.TTLFieldContainer.Spacing = 6;
		// Container child TTLFieldContainer.Gtk.Box+BoxChild
		this.TimeToLiveTextBox = new global::Gtk.Entry ();
		this.TimeToLiveTextBox.CanFocus = true;
		this.TimeToLiveTextBox.Name = "TimeToLiveTextBox";
		this.TimeToLiveTextBox.IsEditable = true;
		this.TimeToLiveTextBox.WidthChars = 10;
		this.TimeToLiveTextBox.InvisibleChar = '●';
		this.TTLFieldContainer.Add (this.TimeToLiveTextBox);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.TTLFieldContainer [this.TimeToLiveTextBox]));
		w29.Position = 0;
		// Container child TTLFieldContainer.Gtk.Box+BoxChild
		this.lbl_Days = new global::Gtk.Label ();
		this.lbl_Days.Name = "lbl_Days";
		this.lbl_Days.LabelProp = global::Mono.Unix.Catalog.GetString ("days");
		this.TTLFieldContainer.Add (this.lbl_Days);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.TTLFieldContainer [this.lbl_Days]));
		w30.Position = 1;
		w30.Expand = false;
		w30.Fill = false;
		this.ResourceDescriptionColumn2.Add (this.TTLFieldContainer);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionColumn2 [this.TTLFieldContainer]));
		w31.Position = 7;
		w31.Expand = false;
		w31.Fill = false;
		this.ResourceDescriptionContainer.Add (this.ResourceDescriptionColumn2);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionContainer [this.ResourceDescriptionColumn2]));
		w32.Position = 1;
		w32.Expand = false;
		w32.Fill = false;
		w32.Padding = ((uint)(5));
		// Container child ResourceDescriptionContainer.Gtk.Box+BoxChild
		this.ResourceDescriptionColumn3 = new global::Gtk.VBox ();
		this.ResourceDescriptionColumn3.Name = "ResourceDescriptionColumn3";
		this.ResourceDescriptionColumn3.Spacing = 6;
		// Container child ResourceDescriptionColumn3.Gtk.Box+BoxChild
		this.lbl_SubmitterType = new global::Gtk.Label ();
		this.lbl_SubmitterType.Name = "lbl_SubmitterType";
		this.lbl_SubmitterType.Xalign = 0F;
		this.lbl_SubmitterType.LabelProp = global::Mono.Unix.Catalog.GetString ("*Submitter Type:");
		this.ResourceDescriptionColumn3.Add (this.lbl_SubmitterType);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionColumn3 [this.lbl_SubmitterType]));
		w33.Position = 0;
		w33.Expand = false;
		w33.Fill = false;
		// Container child ResourceDescriptionColumn3.Gtk.Box+BoxChild
		this.SubmitterTypeComboBox = global::Gtk.ComboBox.NewText ();
		this.SubmitterTypeComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Anonymous"));
		this.SubmitterTypeComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("User"));
		this.SubmitterTypeComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Agent"));
		this.SubmitterTypeComboBox.Name = "SubmitterTypeComboBox";
		this.SubmitterTypeComboBox.Active = 0;
		this.ResourceDescriptionColumn3.Add (this.SubmitterTypeComboBox);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionColumn3 [this.SubmitterTypeComboBox]));
		w34.Position = 1;
		w34.Expand = false;
		w34.Fill = false;
		// Container child ResourceDescriptionColumn3.Gtk.Box+BoxChild
		this.SubmitterNameContainer = new global::Gtk.VBox ();
		this.SubmitterNameContainer.Name = "SubmitterNameContainer";
		this.SubmitterNameContainer.Spacing = 6;
		// Container child SubmitterNameContainer.Gtk.Box+BoxChild
		this.lbl_SubmitterName = new global::Gtk.Label ();
		this.lbl_SubmitterName.Name = "lbl_SubmitterName";
		this.lbl_SubmitterName.Xalign = 0F;
		this.lbl_SubmitterName.LabelProp = global::Mono.Unix.Catalog.GetString ("*Submitter Name:");
		this.SubmitterNameContainer.Add (this.lbl_SubmitterName);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.SubmitterNameContainer [this.lbl_SubmitterName]));
		w35.Position = 0;
		w35.Expand = false;
		w35.Fill = false;
		// Container child SubmitterNameContainer.Gtk.Box+BoxChild
		this.SubmitterNameTextBox = new global::Gtk.Entry ();
		this.SubmitterNameTextBox.CanFocus = true;
		this.SubmitterNameTextBox.Name = "SubmitterNameTextBox";
		this.SubmitterNameTextBox.IsEditable = true;
		this.SubmitterNameTextBox.InvisibleChar = '●';
		this.SubmitterNameContainer.Add (this.SubmitterNameTextBox);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.SubmitterNameContainer [this.SubmitterNameTextBox]));
		w36.Position = 1;
		w36.Expand = false;
		w36.Fill = false;
		this.ResourceDescriptionColumn3.Add (this.SubmitterNameContainer);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionColumn3 [this.SubmitterNameContainer]));
		w37.Position = 2;
		w37.Expand = false;
		w37.Fill = false;
		// Container child ResourceDescriptionColumn3.Gtk.Box+BoxChild
		this.lbl_Curator = new global::Gtk.Label ();
		this.lbl_Curator.Name = "lbl_Curator";
		this.lbl_Curator.Xalign = 0F;
		this.lbl_Curator.LabelProp = global::Mono.Unix.Catalog.GetString ("Curator:");
		this.ResourceDescriptionColumn3.Add (this.lbl_Curator);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionColumn3 [this.lbl_Curator]));
		w38.Position = 3;
		w38.Expand = false;
		w38.Fill = false;
		// Container child ResourceDescriptionColumn3.Gtk.Box+BoxChild
		this.CuratorTextBox = new global::Gtk.Entry ();
		this.CuratorTextBox.CanFocus = true;
		this.CuratorTextBox.Name = "CuratorTextBox";
		this.CuratorTextBox.IsEditable = true;
		this.CuratorTextBox.InvisibleChar = '●';
		this.ResourceDescriptionColumn3.Add (this.CuratorTextBox);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionColumn3 [this.CuratorTextBox]));
		w39.Position = 4;
		w39.Expand = false;
		w39.Fill = false;
		// Container child ResourceDescriptionColumn3.Gtk.Box+BoxChild
		this.lbl_Owner = new global::Gtk.Label ();
		this.lbl_Owner.Name = "lbl_Owner";
		this.lbl_Owner.Xalign = 0F;
		this.lbl_Owner.LabelProp = global::Mono.Unix.Catalog.GetString ("Owner:");
		this.ResourceDescriptionColumn3.Add (this.lbl_Owner);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionColumn3 [this.lbl_Owner]));
		w40.Position = 5;
		w40.Expand = false;
		w40.Fill = false;
		// Container child ResourceDescriptionColumn3.Gtk.Box+BoxChild
		this.OwnerTextBox = new global::Gtk.Entry ();
		this.OwnerTextBox.CanFocus = true;
		this.OwnerTextBox.Name = "OwnerTextBox";
		this.OwnerTextBox.IsEditable = true;
		this.OwnerTextBox.InvisibleChar = '●';
		this.ResourceDescriptionColumn3.Add (this.OwnerTextBox);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionColumn3 [this.OwnerTextBox]));
		w41.Position = 6;
		w41.Expand = false;
		w41.Fill = false;
		// Container child ResourceDescriptionColumn3.Gtk.Box+BoxChild
		this.lbl_Signer = new global::Gtk.Label ();
		this.lbl_Signer.Name = "lbl_Signer";
		this.lbl_Signer.Xalign = 0F;
		this.lbl_Signer.LabelProp = global::Mono.Unix.Catalog.GetString ("Signer:");
		this.ResourceDescriptionColumn3.Add (this.lbl_Signer);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionColumn3 [this.lbl_Signer]));
		w42.Position = 7;
		w42.Expand = false;
		w42.Fill = false;
		// Container child ResourceDescriptionColumn3.Gtk.Box+BoxChild
		this.SignerTextBox = new global::Gtk.Entry ();
		this.SignerTextBox.CanFocus = true;
		this.SignerTextBox.Name = "SignerTextBox";
		this.SignerTextBox.IsEditable = true;
		this.SignerTextBox.InvisibleChar = '●';
		this.ResourceDescriptionColumn3.Add (this.SignerTextBox);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionColumn3 [this.SignerTextBox]));
		w43.Position = 8;
		w43.Expand = false;
		w43.Fill = false;
		this.ResourceDescriptionContainer.Add (this.ResourceDescriptionColumn3);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.ResourceDescriptionContainer [this.ResourceDescriptionColumn3]));
		w44.Position = 2;
		w44.Expand = false;
		w44.Fill = false;
		w44.Padding = ((uint)(10));
		this.RootNotebook.Add (this.ResourceDescriptionContainer);
		// Notebook tab
		this.lbl_nb_ResourceDescription = new global::Gtk.Label ();
		this.lbl_nb_ResourceDescription.Name = "lbl_nb_ResourceDescription";
		this.lbl_nb_ResourceDescription.LabelProp = global::Mono.Unix.Catalog.GetString ("Resource Description");
		this.RootNotebook.SetTabLabel (this.ResourceDescriptionContainer, this.lbl_nb_ResourceDescription);
		this.lbl_nb_ResourceDescription.ShowAll ();
		// Container child RootNotebook.Gtk.Notebook+NotebookChild
		this.TermsOfServiceContainer = new global::Gtk.VBox ();
		this.TermsOfServiceContainer.Name = "TermsOfServiceContainer";
		this.TermsOfServiceContainer.Spacing = 6;
		this.TermsOfServiceContainer.BorderWidth = ((uint)(9));
		// Container child TermsOfServiceContainer.Gtk.Box+BoxChild
		this.lbl_TermsOfServiceUrl = new global::Gtk.Label ();
		this.lbl_TermsOfServiceUrl.Name = "lbl_TermsOfServiceUrl";
		this.lbl_TermsOfServiceUrl.Xalign = 0F;
		this.lbl_TermsOfServiceUrl.LabelProp = global::Mono.Unix.Catalog.GetString ("Terms of Service Url:");
		this.TermsOfServiceContainer.Add (this.lbl_TermsOfServiceUrl);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.TermsOfServiceContainer [this.lbl_TermsOfServiceUrl]));
		w46.Position = 0;
		w46.Expand = false;
		w46.Fill = false;
		// Container child TermsOfServiceContainer.Gtk.Box+BoxChild
		this.TermsOfServiceTextBox = new global::Gtk.Entry ();
		this.TermsOfServiceTextBox.CanFocus = true;
		this.TermsOfServiceTextBox.Name = "TermsOfServiceTextBox";
		this.TermsOfServiceTextBox.IsEditable = true;
		this.TermsOfServiceTextBox.InvisibleChar = '●';
		this.TermsOfServiceContainer.Add (this.TermsOfServiceTextBox);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.TermsOfServiceContainer [this.TermsOfServiceTextBox]));
		w47.Position = 1;
		w47.Expand = false;
		w47.Fill = false;
		// Container child TermsOfServiceContainer.Gtk.Box+BoxChild
		this.lbl_AttributionStatement = new global::Gtk.Label ();
		this.lbl_AttributionStatement.Name = "lbl_AttributionStatement";
		this.lbl_AttributionStatement.Xalign = 0F;
		this.lbl_AttributionStatement.LabelProp = global::Mono.Unix.Catalog.GetString ("Attribution Statement:");
		this.TermsOfServiceContainer.Add (this.lbl_AttributionStatement);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.TermsOfServiceContainer [this.lbl_AttributionStatement]));
		w48.Position = 2;
		w48.Expand = false;
		w48.Fill = false;
		// Container child TermsOfServiceContainer.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.AttributionStatementTextView = new global::Gtk.TextView ();
		this.AttributionStatementTextView.CanFocus = true;
		this.AttributionStatementTextView.Name = "AttributionStatementTextView";
		this.GtkScrolledWindow.Add (this.AttributionStatementTextView);
		this.TermsOfServiceContainer.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.TermsOfServiceContainer [this.GtkScrolledWindow]));
		w50.Position = 3;
		this.RootNotebook.Add (this.TermsOfServiceContainer);
		global::Gtk.Notebook.NotebookChild w51 = ((global::Gtk.Notebook.NotebookChild)(this.RootNotebook [this.TermsOfServiceContainer]));
		w51.Position = 1;
		// Notebook tab
		this.lbl_nb_TermsOfService = new global::Gtk.Label ();
		this.lbl_nb_TermsOfService.Name = "lbl_nb_TermsOfService";
		this.lbl_nb_TermsOfService.LabelProp = global::Mono.Unix.Catalog.GetString ("Terms Of Service");
		this.RootNotebook.SetTabLabel (this.TermsOfServiceContainer, this.lbl_nb_TermsOfService);
		this.lbl_nb_TermsOfService.ShowAll ();
		// Container child RootNotebook.Gtk.Notebook+NotebookChild
		this.SignatureInformationWidget = new global::SignatureInformationWidget ();
		this.SignatureInformationWidget.Events = ((global::Gdk.EventMask)(256));
		this.SignatureInformationWidget.Name = "SignatureInformationWidget";
		this.RootNotebook.Add (this.SignatureInformationWidget);
		global::Gtk.Notebook.NotebookChild w52 = ((global::Gtk.Notebook.NotebookChild)(this.RootNotebook [this.SignatureInformationWidget]));
		w52.Position = 2;
		// Notebook tab
		this.lbl_nb_SignatureInformation = new global::Gtk.Label ();
		this.lbl_nb_SignatureInformation.Name = "lbl_nb_SignatureInformation";
		this.lbl_nb_SignatureInformation.LabelProp = global::Mono.Unix.Catalog.GetString ("Signature Information");
		this.RootNotebook.SetTabLabel (this.SignatureInformationWidget, this.lbl_nb_SignatureInformation);
		this.lbl_nb_SignatureInformation.ShowAll ();
		// Container child RootNotebook.Gtk.Notebook+NotebookChild
		this.NodeInformationContainer = new global::Gtk.HBox ();
		this.NodeInformationContainer.Name = "NodeInformationContainer";
		this.NodeInformationContainer.Spacing = 6;
		this.NodeInformationContainer.BorderWidth = ((uint)(9));
		// Container child NodeInformationContainer.Gtk.Box+BoxChild
		this.NodeInfo = new global::NodeInfoWidget ();
		this.NodeInfo.Events = ((global::Gdk.EventMask)(256));
		this.NodeInfo.Name = "NodeInfo";
		this.NodeInformationContainer.Add (this.NodeInfo);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.NodeInformationContainer [this.NodeInfo]));
		w53.Position = 0;
		w53.Expand = false;
		w53.Fill = false;
		this.RootNotebook.Add (this.NodeInformationContainer);
		global::Gtk.Notebook.NotebookChild w54 = ((global::Gtk.Notebook.NotebookChild)(this.RootNotebook [this.NodeInformationContainer]));
		w54.Position = 3;
		// Notebook tab
		this.lbl_nb_NodeInformation = new global::Gtk.Label ();
		this.lbl_nb_NodeInformation.Name = "lbl_nb_NodeInformation";
		this.lbl_nb_NodeInformation.LabelProp = global::Mono.Unix.Catalog.GetString ("Node Information");
		this.RootNotebook.SetTabLabel (this.NodeInformationContainer, this.lbl_nb_NodeInformation);
		this.lbl_nb_NodeInformation.ShowAll ();
		this.MainVerticalPane.Add (this.RootNotebook);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.MainVerticalPane [this.RootNotebook]));
		w55.Position = 1;
		w55.Expand = false;
		w55.Padding = ((uint)(10));
		// Container child MainVerticalPane.Gtk.Box+BoxChild
		this.RequiredFieldNotificationContainer = new global::Gtk.HBox ();
		this.RequiredFieldNotificationContainer.Name = "RequiredFieldNotificationContainer";
		this.RequiredFieldNotificationContainer.Spacing = 6;
		// Container child RequiredFieldNotificationContainer.Gtk.Box+BoxChild
		this.lbl_requiredFieldsNotifier = new global::Gtk.Label ();
		this.lbl_requiredFieldsNotifier.Name = "lbl_requiredFieldsNotifier";
		this.lbl_requiredFieldsNotifier.Xalign = 1F;
		this.lbl_requiredFieldsNotifier.LabelProp = global::Mono.Unix.Catalog.GetString ("Note: * indicates a required field");
		this.lbl_requiredFieldsNotifier.Justify = ((global::Gtk.Justification)(1));
		this.RequiredFieldNotificationContainer.Add (this.lbl_requiredFieldsNotifier);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.RequiredFieldNotificationContainer [this.lbl_requiredFieldsNotifier]));
		w56.Position = 2;
		w56.Padding = ((uint)(5));
		this.MainVerticalPane.Add (this.RequiredFieldNotificationContainer);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.MainVerticalPane [this.RequiredFieldNotificationContainer]));
		w57.Position = 2;
		w57.Expand = false;
		w57.Fill = false;
		// Container child MainVerticalPane.Gtk.Box+BoxChild
		this.lbl_ConsoleOutput = new global::Gtk.Label ();
		this.lbl_ConsoleOutput.Name = "lbl_ConsoleOutput";
		this.lbl_ConsoleOutput.Xalign = 0F;
		this.lbl_ConsoleOutput.LabelProp = global::Mono.Unix.Catalog.GetString ("Console Output:");
		this.lbl_ConsoleOutput.UseMarkup = true;
		this.MainVerticalPane.Add (this.lbl_ConsoleOutput);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.MainVerticalPane [this.lbl_ConsoleOutput]));
		w58.Position = 3;
		w58.Expand = false;
		w58.Fill = false;
		// Container child MainVerticalPane.Gtk.Box+BoxChild
		this.ConsoleContainer = new global::Gtk.ScrolledWindow ();
		this.ConsoleContainer.Name = "ConsoleContainer";
		this.ConsoleContainer.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child ConsoleContainer.Gtk.Container+ContainerChild
		this.ConsoleWindow = new global::Gtk.TextView ();
		this.ConsoleWindow.CanFocus = true;
		this.ConsoleWindow.Name = "ConsoleWindow";
		this.ConsoleWindow.Editable = false;
		this.ConsoleWindow.CursorVisible = false;
		this.ConsoleWindow.WrapMode = ((global::Gtk.WrapMode)(1));
		this.ConsoleContainer.Add (this.ConsoleWindow);
		this.MainVerticalPane.Add (this.ConsoleContainer);
		global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.MainVerticalPane [this.ConsoleContainer]));
		w60.Position = 4;
		this.Add (this.MainVerticalPane);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 639;
		this.DefaultHeight = 619;
		this.PayloadLocatorContainer.Hide ();
		this.PayloadEditorButtonBox.Hide ();
		this.SubmitterNameContainer.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.OpenResourceDescriptionAction.Activated += new global::System.EventHandler (this.LoadResourceDescriptionDocument);
		this.SaveResourceDescriptionAction.Activated += new global::System.EventHandler (this.SaveResourceDescriptionDocument);
		this.PublishCurrentDocumentAction.Activated += new global::System.EventHandler (this.PublishDocument);
		this.NewAction.Activated += new global::System.EventHandler (this.ResetFields);
		this.PublishFromCSVAction.Activated += new global::System.EventHandler (this.OnPublishFromCSVActionActivated);
		this.ViewPublishHistoryAction.Activated += new global::System.EventHandler (this.CreateHistoryWindow);
		this.PayloadPlacementComboBox.Changed += new global::System.EventHandler (this.UpdatePayloadChooseContainer);
		this.PayloadFileChooser.SelectionChanged += new global::System.EventHandler (this.OnPayloadFileChooserSelectionChanged);
		this.EditPayloadButton.Clicked += new global::System.EventHandler (this.CreateEditPayloadPopup);
		this.ChoosePayloadFileButton.Clicked += new global::System.EventHandler (this.ChooseNewPayloadFile);
		this.SubmitterTypeComboBox.Changed += new global::System.EventHandler (this.UpdateSubmitterNameVisibility);
	}
}
