
// This file has been generated by the GUI designer. Do not modify.

public partial class NodeInfoWidget
{
	private global::Gtk.HBox NodeInformationContainer;
	private global::Gtk.VBox NodeInfoColumn;
	private global::Gtk.Label lbl_NodeUrl;
	private global::Gtk.HBox NodeUrlTextContainer;
	private global::Gtk.Label lbl_http;
	private global::Gtk.Entry NodeUrlTextBox;
	private global::Gtk.Label lbl_trailingSlash;
	private global::Gtk.Label lbl_AuthType;
	private global::Gtk.ComboBox AuthTypeComboBox;
	private global::Gtk.VBox AuthCredentialsContainer;
	private global::Gtk.Label lbl_AuthUsername;
	private global::Gtk.Entry AuthUsernameTextBox;
	private global::Gtk.Label lbl_AuthPassword;
	private global::Gtk.Entry AuthPasswordTextBox;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget NodeInfoWidget
		global::Stetic.BinContainer.Attach (this);
		this.Name = "NodeInfoWidget";
		// Container child NodeInfoWidget.Gtk.Container+ContainerChild
		this.NodeInformationContainer = new global::Gtk.HBox ();
		this.NodeInformationContainer.Name = "NodeInformationContainer";
		this.NodeInformationContainer.Spacing = 6;
		this.NodeInformationContainer.BorderWidth = ((uint)(9));
		// Container child NodeInformationContainer.Gtk.Box+BoxChild
		this.NodeInfoColumn = new global::Gtk.VBox ();
		this.NodeInfoColumn.Name = "NodeInfoColumn";
		this.NodeInfoColumn.Spacing = 6;
		// Container child NodeInfoColumn.Gtk.Box+BoxChild
		this.lbl_NodeUrl = new global::Gtk.Label ();
		this.lbl_NodeUrl.Name = "lbl_NodeUrl";
		this.lbl_NodeUrl.Xalign = 0F;
		this.lbl_NodeUrl.LabelProp = global::Mono.Unix.Catalog.GetString ("*Node Url:");
		this.NodeInfoColumn.Add (this.lbl_NodeUrl);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.NodeInfoColumn [this.lbl_NodeUrl]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child NodeInfoColumn.Gtk.Box+BoxChild
		this.NodeUrlTextContainer = new global::Gtk.HBox ();
		this.NodeUrlTextContainer.Name = "NodeUrlTextContainer";
		this.NodeUrlTextContainer.Spacing = 6;
		// Container child NodeUrlTextContainer.Gtk.Box+BoxChild
		this.lbl_http = new global::Gtk.Label ();
		this.lbl_http.Name = "lbl_http";
		this.lbl_http.LabelProp = global::Mono.Unix.Catalog.GetString ("http://");
		this.NodeUrlTextContainer.Add (this.lbl_http);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.NodeUrlTextContainer [this.lbl_http]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child NodeUrlTextContainer.Gtk.Box+BoxChild
		this.NodeUrlTextBox = new global::Gtk.Entry ();
		this.NodeUrlTextBox.CanFocus = true;
		this.NodeUrlTextBox.Name = "NodeUrlTextBox";
		this.NodeUrlTextBox.IsEditable = true;
		this.NodeUrlTextBox.InvisibleChar = '●';
		this.NodeUrlTextContainer.Add (this.NodeUrlTextBox);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.NodeUrlTextContainer [this.NodeUrlTextBox]));
		w3.Position = 1;
		// Container child NodeUrlTextContainer.Gtk.Box+BoxChild
		this.lbl_trailingSlash = new global::Gtk.Label ();
		this.lbl_trailingSlash.Name = "lbl_trailingSlash";
		this.lbl_trailingSlash.LabelProp = global::Mono.Unix.Catalog.GetString ("/");
		this.NodeUrlTextContainer.Add (this.lbl_trailingSlash);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.NodeUrlTextContainer [this.lbl_trailingSlash]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.NodeInfoColumn.Add (this.NodeUrlTextContainer);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.NodeInfoColumn [this.NodeUrlTextContainer]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child NodeInfoColumn.Gtk.Box+BoxChild
		this.lbl_AuthType = new global::Gtk.Label ();
		this.lbl_AuthType.Name = "lbl_AuthType";
		this.lbl_AuthType.Xalign = 0F;
		this.lbl_AuthType.LabelProp = global::Mono.Unix.Catalog.GetString ("Auth Type:");
		this.NodeInfoColumn.Add (this.lbl_AuthType);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.NodeInfoColumn [this.lbl_AuthType]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		// Container child NodeInfoColumn.Gtk.Box+BoxChild
		this.AuthTypeComboBox = global::Gtk.ComboBox.NewText ();
		this.AuthTypeComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("None"));
		this.AuthTypeComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("HTTP Basic"));
		this.AuthTypeComboBox.Name = "AuthTypeComboBox";
		this.AuthTypeComboBox.Active = 0;
		this.NodeInfoColumn.Add (this.AuthTypeComboBox);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.NodeInfoColumn [this.AuthTypeComboBox]));
		w7.Position = 3;
		w7.Expand = false;
		w7.Fill = false;
		// Container child NodeInfoColumn.Gtk.Box+BoxChild
		this.AuthCredentialsContainer = new global::Gtk.VBox ();
		this.AuthCredentialsContainer.Name = "AuthCredentialsContainer";
		this.AuthCredentialsContainer.Spacing = 6;
		// Container child AuthCredentialsContainer.Gtk.Box+BoxChild
		this.lbl_AuthUsername = new global::Gtk.Label ();
		this.lbl_AuthUsername.Name = "lbl_AuthUsername";
		this.lbl_AuthUsername.Xalign = 0F;
		this.lbl_AuthUsername.LabelProp = global::Mono.Unix.Catalog.GetString ("Username:");
		this.AuthCredentialsContainer.Add (this.lbl_AuthUsername);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.AuthCredentialsContainer [this.lbl_AuthUsername]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child AuthCredentialsContainer.Gtk.Box+BoxChild
		this.AuthUsernameTextBox = new global::Gtk.Entry ();
		this.AuthUsernameTextBox.CanFocus = true;
		this.AuthUsernameTextBox.Name = "AuthUsernameTextBox";
		this.AuthUsernameTextBox.IsEditable = true;
		this.AuthUsernameTextBox.InvisibleChar = '●';
		this.AuthCredentialsContainer.Add (this.AuthUsernameTextBox);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.AuthCredentialsContainer [this.AuthUsernameTextBox]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child AuthCredentialsContainer.Gtk.Box+BoxChild
		this.lbl_AuthPassword = new global::Gtk.Label ();
		this.lbl_AuthPassword.Name = "lbl_AuthPassword";
		this.lbl_AuthPassword.Xalign = 0F;
		this.lbl_AuthPassword.LabelProp = global::Mono.Unix.Catalog.GetString ("Password:");
		this.AuthCredentialsContainer.Add (this.lbl_AuthPassword);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.AuthCredentialsContainer [this.lbl_AuthPassword]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		// Container child AuthCredentialsContainer.Gtk.Box+BoxChild
		this.AuthPasswordTextBox = new global::Gtk.Entry ();
		this.AuthPasswordTextBox.CanFocus = true;
		this.AuthPasswordTextBox.Name = "AuthPasswordTextBox";
		this.AuthPasswordTextBox.IsEditable = true;
		this.AuthPasswordTextBox.InvisibleChar = '●';
		this.AuthCredentialsContainer.Add (this.AuthPasswordTextBox);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.AuthCredentialsContainer [this.AuthPasswordTextBox]));
		w11.Position = 3;
		w11.Expand = false;
		w11.Fill = false;
		this.NodeInfoColumn.Add (this.AuthCredentialsContainer);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.NodeInfoColumn [this.AuthCredentialsContainer]));
		w12.Position = 4;
		w12.Expand = false;
		w12.Fill = false;
		this.NodeInformationContainer.Add (this.NodeInfoColumn);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.NodeInformationContainer [this.NodeInfoColumn]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		this.Add (this.NodeInformationContainer);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.AuthCredentialsContainer.Hide ();
		this.Hide ();
	}
}
